title: Rayalan Kenyon
author: Rayalan Kenyon
email: rayalan.kenyon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a programming with a wide range of interests.
  Check out my work! 

twitter_username: Rayalan_Kenyon
github_username:  rayalankenyon

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%B %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
